name: attrition-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - shap
  - imbalanced-learn
  - jupyter
  - notebook
  - statsmodels
